### PR TITLE
Improved logic

### PR DESCRIPTION
**Pull request by dreadpool2**

### CODE REVIEW

**Comment by simarsingh24** [comment]
@dreadpool2 cant make any sense from the title, please make sure everything is understandable

**Comment by dreadpool2** [comment]
@simarsingh24 well previous files also got added to this. Now its resolved

**Comment by simarsingh24** [comment]
this is not a good way to access token , the sole purpose of using shared pref is that we dont have to keep a static varibale for accesing token,
leave this on me i will solve this

**Comment by dreadpool2** [comment]
great :+1:

**Pull request closed without merging**
